import { db } from '@/db';
import { complaints } from '@/db/schema';

async function main() {
    const sampleComplaints = [
        // ELECTRICAL (4 complaints)
        {
            title: 'Fan not working in Classroom 305',
            description: 'The ceiling fan in Classroom 305 has stopped working completely. Students are facing difficulty during classes due to heat. The switch has been checked and seems fine.',
            category: 'electrical',
            difficulty: 'easy',
            emergency: false,
            fixTillDate: new Date('2024-02-25').toISOString(),
            photo: null,
            status: 'resolved',
            raisedBy: 3,
            raisedByName: 'Priya Sharma',
            raisedByBranch: 'Electronics',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=5',
            volunteerId: 16,
            volunteerName: 'Rajesh Kumar',
            createdAt: new Date('2024-02-20').toISOString(),
            resolvedAt: new Date('2024-02-22').toISOString(),
        },
        {
            title: 'Power outage in Hostel Block A',
            description: 'Complete power failure in Hostel Block A affecting all rooms on floors 2 and 3. Students are unable to study or charge their devices. This is an urgent situation requiring immediate attention.',
            category: 'electrical',
            difficulty: 'hard',
            emergency: true,
            fixTillDate: new Date('2024-02-23').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Power+Outage',
            status: 'in-progress',
            raisedBy: 7,
            raisedByName: 'Arjun Patel',
            raisedByBranch: 'Mechanical',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=12',
            volunteerId: 16,
            volunteerName: 'Rajesh Kumar',
            createdAt: new Date('2024-02-20').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Flickering lights in Library Reading Room',
            description: 'The tube lights in the main reading room of the library have been flickering constantly for the past two days. This is causing strain on students eyes and making it difficult to concentrate on studies.',
            category: 'electrical',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-27').toISOString(),
            photo: null,
            status: 'open',
            raisedBy: 11,
            raisedByName: 'Kavya Reddy',
            raisedByBranch: 'Civil',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=9',
            volunteerId: null,
            volunteerName: null,
            createdAt: new Date('2024-02-22').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'AC not cooling in Computer Lab 2',
            description: 'The air conditioning unit in Computer Lab 2 is running but not providing adequate cooling. Room temperature is getting too high for comfortable lab sessions. The AC is making unusual noises.',
            category: 'electrical',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-26').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=AC+Issue',
            status: 'resolved',
            raisedBy: 5,
            raisedByName: 'Sneha Gupta',
            raisedByBranch: 'CSE',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=10',
            volunteerId: 16,
            volunteerName: 'Rajesh Kumar',
            createdAt: new Date('2024-02-19').toISOString(),
            resolvedAt: new Date('2024-02-21').toISOString(),
        },

        // MECHANICAL (4 complaints)
        {
            title: 'Broken door handle in Cafeteria',
            description: 'The main entrance door handle of the cafeteria is broken and loose. Students are having difficulty opening and closing the door properly. This needs to be fixed soon as its a high-traffic area.',
            category: 'mechanical',
            difficulty: 'easy',
            emergency: false,
            fixTillDate: new Date('2024-02-24').toISOString(),
            photo: null,
            status: 'resolved',
            raisedBy: 2,
            raisedByName: 'Rahul Verma',
            raisedByBranch: 'CSE',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=33',
            volunteerId: 17,
            volunteerName: 'Amit Singh',
            createdAt: new Date('2024-02-18').toISOString(),
            resolvedAt: new Date('2024-02-20').toISOString(),
        },
        {
            title: 'Water cooler leaking in Admin Block',
            description: 'The water cooler on the ground floor of Admin Block is leaking continuously, creating a puddle on the floor. This is causing a slipping hazard and water wastage. The leak appears to be from the bottom connection.',
            category: 'mechanical',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-26').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Water+Cooler+Leak',
            status: 'in-progress',
            raisedBy: 9,
            raisedByName: 'Anjali Mehta',
            raisedByBranch: 'IT',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=45',
            volunteerId: 17,
            volunteerName: 'Amit Singh',
            createdAt: new Date('2024-02-21').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Elevator stuck on 3rd floor',
            description: 'The main elevator in the academic block is stuck on the 3rd floor and not responding to any floor calls. This is causing major inconvenience especially for differently-abled students and faculty. Urgent repair needed.',
            category: 'mechanical',
            difficulty: 'hard',
            emergency: true,
            fixTillDate: new Date('2024-02-22').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Elevator+Stuck',
            status: 'resolved',
            raisedBy: 12,
            raisedByName: 'Vikram Joshi',
            raisedByBranch: 'Mechanical',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=51',
            volunteerId: 17,
            volunteerName: 'Amit Singh',
            createdAt: new Date('2024-02-17').toISOString(),
            resolvedAt: new Date('2024-02-19').toISOString(),
        },
        {
            title: 'Loose window pane in Hostel Room 204',
            description: 'The window pane in Hostel Room 204 has become loose and rattles with wind. There is a safety concern as the pane might fall. The frame also needs tightening.',
            category: 'mechanical',
            difficulty: 'easy',
            emergency: false,
            fixTillDate: new Date('2024-02-23').toISOString(),
            photo: null,
            status: 'closed',
            raisedBy: 8,
            raisedByName: 'Neha Singh',
            raisedByBranch: 'Electronics',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=47',
            volunteerId: 17,
            volunteerName: 'Amit Singh',
            createdAt: new Date('2024-02-15').toISOString(),
            resolvedAt: new Date('2024-02-17').toISOString(),
        },

        // NETWORKING (4 complaints)
        {
            title: 'WiFi not working in Library',
            description: 'The WiFi connection in the library is completely down. Students are unable to access online resources and digital library materials. The router appears to be functioning but no devices can connect.',
            category: 'networking',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-25').toISOString(),
            photo: null,
            status: 'in-progress',
            raisedBy: 4,
            raisedByName: 'Aditya Kumar',
            raisedByBranch: 'IT',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=13',
            volunteerId: 18,
            volunteerName: 'Priya Iyer',
            createdAt: new Date('2024-02-21').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Ethernet ports dead in Lab 401',
            description: 'All ethernet ports in Computer Lab 401 are non-functional. Students cannot connect their laptops for practical sessions. The switch needs to be checked and possibly replaced. This is affecting multiple lab sessions.',
            category: 'networking',
            difficulty: 'hard',
            emergency: false,
            fixTillDate: new Date('2024-02-28').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Ethernet+Ports',
            status: 'open',
            raisedBy: 6,
            raisedByName: 'Riya Malhotra',
            raisedByBranch: 'CSE',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=16',
            volunteerId: null,
            volunteerName: null,
            createdAt: new Date('2024-02-22').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Slow internet speed in Hostel Block B',
            description: 'Internet speed in Hostel Block B has been extremely slow for the past week. Students are facing issues with online classes and downloading study materials. Speed test shows less than 1 Mbps consistently.',
            category: 'networking',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-27').toISOString(),
            photo: null,
            status: 'in-progress',
            raisedBy: 13,
            raisedByName: 'Karan Desai',
            raisedByBranch: 'Civil',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=52',
            volunteerId: 18,
            volunteerName: 'Priya Iyer',
            createdAt: new Date('2024-02-20').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Router configuration issue in Department Office',
            description: 'The router in the Electronics Department office needs reconfiguration. Some faculty members are unable to access department servers and printers. Password reset might be required.',
            category: 'networking',
            difficulty: 'easy',
            emergency: false,
            fixTillDate: new Date('2024-02-24').toISOString(),
            photo: null,
            status: 'resolved',
            raisedBy: 10,
            raisedByName: 'Deepak Rao',
            raisedByBranch: 'IT',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=60',
            volunteerId: 18,
            volunteerName: 'Priya Iyer',
            createdAt: new Date('2024-02-19').toISOString(),
            resolvedAt: new Date('2024-02-21').toISOString(),
        },

        // PLUMBING (4 complaints)
        {
            title: 'Tap leaking in Boys Washroom Ground Floor',
            description: 'One of the taps in the boys washroom on ground floor is continuously leaking. This is causing water wastage and the floor remains wet creating slipping hazard. The tap handle seems loose.',
            category: 'plumbing',
            difficulty: 'easy',
            emergency: false,
            fixTillDate: new Date('2024-02-25').toISOString(),
            photo: null,
            status: 'resolved',
            raisedBy: 1,
            raisedByName: 'Aarav Sharma',
            raisedByBranch: 'CSE',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=32',
            volunteerId: 19,
            volunteerName: 'Suresh Nair',
            createdAt: new Date('2024-02-18').toISOString(),
            resolvedAt: new Date('2024-02-20').toISOString(),
        },
        {
            title: 'Drain blocked in Hostel Kitchen',
            description: 'The main drain in the hostel kitchen is completely blocked causing water to overflow. Kitchen staff are unable to work properly and there is a foul smell developing. This needs urgent attention.',
            category: 'plumbing',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-26').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Blocked+Drain',
            status: 'open',
            raisedBy: 14,
            raisedByName: 'Pooja Nair',
            raisedByBranch: 'Mechanical',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=26',
            volunteerId: null,
            volunteerName: null,
            createdAt: new Date('2024-02-21').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Water pressure very low in Girls Hostel',
            description: 'Water pressure in the girls hostel has dropped significantly. Students on upper floors are getting very little water especially during morning and evening hours. This is an urgent issue affecting daily routine of many students.',
            category: 'plumbing',
            difficulty: 'hard',
            emergency: true,
            fixTillDate: new Date('2024-02-24').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Low+Water+Pressure',
            status: 'in-progress',
            raisedBy: 15,
            raisedByName: 'Simran Kaur',
            raisedByBranch: 'Electronics',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=24',
            volunteerId: 19,
            volunteerName: 'Suresh Nair',
            createdAt: new Date('2024-02-20').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Toilet flush not working in Admin Block',
            description: 'The flush in the second cubicle of admin block washroom is not working. The handle is broken and needs replacement. This is causing inconvenience to staff and visitors.',
            category: 'plumbing',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-23').toISOString(),
            photo: null,
            status: 'closed',
            raisedBy: 3,
            raisedByName: 'Priya Sharma',
            raisedByBranch: 'Electronics',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=5',
            volunteerId: 19,
            volunteerName: 'Suresh Nair',
            createdAt: new Date('2024-02-16').toISOString(),
            resolvedAt: new Date('2024-02-18').toISOString(),
        },

        // CIVIL (3 complaints)
        {
            title: 'Broken tiles near Main Gate',
            description: 'Several tiles near the main gate entrance are broken and cracked. This creates a tripping hazard for students and visitors entering the campus. The area needs proper repair and replacement of damaged tiles.',
            category: 'civil',
            difficulty: 'medium',
            emergency: false,
            fixTillDate: new Date('2024-02-28').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Broken+Tiles',
            status: 'open',
            raisedBy: 11,
            raisedByName: 'Kavya Reddy',
            raisedByBranch: 'Civil',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=9',
            volunteerId: null,
            volunteerName: null,
            createdAt: new Date('2024-02-22').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Wall crack in Classroom Building',
            description: 'A significant crack has appeared on the wall of the second floor corridor in the main classroom building. The crack seems to be widening and there are concerns about structural safety. Professional inspection needed urgently.',
            category: 'civil',
            difficulty: 'hard',
            emergency: false,
            fixTillDate: new Date('2024-02-29').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Wall+Crack',
            status: 'in-progress',
            raisedBy: 13,
            raisedByName: 'Karan Desai',
            raisedByBranch: 'Civil',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=52',
            volunteerId: 20,
            volunteerName: 'Anita Deshmukh',
            createdAt: new Date('2024-02-19').toISOString(),
            resolvedAt: null,
        },
        {
            title: 'Damaged ceiling in Auditorium',
            description: 'Part of the false ceiling in the auditorium has come loose and is hanging dangerously. There is risk of it falling during events. This is a safety emergency and the auditorium should be closed until repairs are completed.',
            category: 'civil',
            difficulty: 'hard',
            emergency: true,
            fixTillDate: new Date('2024-02-23').toISOString(),
            photo: 'https://via.placeholder.com/400x300?text=Ceiling+Damage',
            status: 'open',
            raisedBy: 7,
            raisedByName: 'Arjun Patel',
            raisedByBranch: 'Mechanical',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=12',
            volunteerId: null,
            volunteerName: null,
            createdAt: new Date('2024-02-21').toISOString(),
            resolvedAt: null,
        },

        // OTHER (1 complaint)
        {
            title: 'Lost and found item - Laptop charger',
            description: 'Found a laptop charger (HP brand) in Library Reading Room yesterday evening. The owner can contact to claim it by providing the charger specifications and proof of ownership.',
            category: 'other',
            difficulty: 'easy',
            emergency: false,
            fixTillDate: new Date('2024-02-27').toISOString(),
            photo: null,
            status: 'resolved',
            raisedBy: 6,
            raisedByName: 'Riya Malhotra',
            raisedByBranch: 'CSE',
            raisedByProfilePic: 'https://i.pravatar.cc/150?img=16',
            volunteerId: 16,
            volunteerName: 'Rajesh Kumar',
            createdAt: new Date('2024-02-20').toISOString(),
            resolvedAt: new Date('2024-02-22').toISOString(),
        },
    ];

    await db.insert(complaints).values(sampleComplaints);
    
    console.log('✅ Complaints seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});