import { db } from '@/db';
import { users } from '@/db/schema';

async function main() {
    const sampleUsers = [
        // STUDENTS (15 records)
        {
            email: 'rahul.sharma@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Rahul Sharma',
            branch: 'CSE',
            rollNumber: '2021CSE001',
            semester: '6',
            year: '2021',
            gender: 'male',
            dob: '2002-05-15',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=rahul',
            phoneNumber: '+91-9876543210',
            department: null,
            points: 125,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            email: 'priya.singh@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Priya Singh',
            branch: 'CSE',
            rollNumber: '2022CSE015',
            semester: '4',
            year: '2022',
            gender: 'female',
            dob: '2003-08-22',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=priya',
            phoneNumber: '+91-9765432109',
            department: null,
            points: 85,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            email: 'amit.patel@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Amit Patel',
            branch: 'Electronics',
            rollNumber: '2021ECE008',
            semester: '6',
            year: '2021',
            gender: 'male',
            dob: '2002-03-10',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=amit',
            phoneNumber: '+91-9654321098',
            department: null,
            points: 140,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            email: 'sneha.gupta@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Sneha Gupta',
            branch: 'Electronics',
            rollNumber: '2022ECE022',
            semester: '4',
            year: '2022',
            gender: 'female',
            dob: '2003-11-05',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=sneha',
            phoneNumber: '+91-9543210987',
            department: null,
            points: 65,
            createdAt: new Date('2024-03-05').toISOString(),
        },
        {
            email: 'arjun.kumar@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Arjun Kumar',
            branch: 'Mechanical',
            rollNumber: '2021MECH007',
            semester: '6',
            year: '2021',
            gender: 'male',
            dob: '2002-07-18',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=arjun',
            phoneNumber: '+91-9432109876',
            department: null,
            points: 95,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            email: 'neha.verma@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Neha Verma',
            branch: 'Mechanical',
            rollNumber: '2022MECH019',
            semester: '4',
            year: '2022',
            gender: 'female',
            dob: '2003-04-12',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=neha',
            phoneNumber: '+91-9321098765',
            department: null,
            points: 110,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            email: 'rohan.desai@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Rohan Desai',
            branch: 'Electrical',
            rollNumber: '2021EEE012',
            semester: '7',
            year: '2021',
            gender: 'male',
            dob: '2002-09-25',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=rohan',
            phoneNumber: '+91-9210987654',
            department: null,
            points: 150,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            email: 'anjali.reddy@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Anjali Reddy',
            branch: 'Electrical',
            rollNumber: '2022EEE028',
            semester: '5',
            year: '2022',
            gender: 'female',
            dob: '2003-06-30',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=anjali',
            phoneNumber: '+91-9109876543',
            department: null,
            points: 75,
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            email: 'vikram.joshi@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Vikram Joshi',
            branch: 'Civil',
            rollNumber: '2021CIV005',
            semester: '7',
            year: '2021',
            gender: 'male',
            dob: '2002-12-08',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=vikram',
            phoneNumber: '+91-9098765432',
            department: null,
            points: 130,
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            email: 'pooja.mehta@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Pooja Mehta',
            branch: 'Civil',
            rollNumber: '2022CIV017',
            semester: '5',
            year: '2022',
            gender: 'female',
            dob: '2003-02-14',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=pooja',
            phoneNumber: '+91-8987654321',
            department: null,
            points: 55,
            createdAt: new Date('2024-03-10').toISOString(),
        },
        {
            email: 'karan.agarwal@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Karan Agarwal',
            branch: 'CSE',
            rollNumber: '2023CSE025',
            semester: '3',
            year: '2023',
            gender: 'male',
            dob: '2004-01-20',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=karan',
            phoneNumber: '+91-8876543210',
            department: null,
            points: 45,
            createdAt: new Date('2024-04-05').toISOString(),
        },
        {
            email: 'divya.iyer@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Divya Iyer',
            branch: 'Electronics',
            rollNumber: '2023ECE031',
            semester: '3',
            year: '2023',
            gender: 'female',
            dob: '2004-10-18',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=divya',
            phoneNumber: '+91-8765432109',
            department: null,
            points: 30,
            createdAt: new Date('2024-05-12').toISOString(),
        },
        {
            email: 'siddharth.rao@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Siddharth Rao',
            branch: 'Mechanical',
            rollNumber: '2023MECH014',
            semester: '3',
            year: '2023',
            gender: 'male',
            dob: '2004-05-27',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=siddharth',
            phoneNumber: '+91-8654321098',
            department: null,
            points: 20,
            createdAt: new Date('2024-06-01').toISOString(),
        },
        {
            email: 'kavya.nair@student.college.edu',
            password: 'password123',
            role: 'student',
            name: 'Kavya Nair',
            branch: 'Electrical',
            rollNumber: '2021EEE034',
            semester: '8',
            year: '2021',
            gender: 'female',
            dob: '2002-11-03',
            profilePicture: 'https://avatar.iran.liara.run/public/girl?username=kavya',
            phoneNumber: '+91-8543210987',
            department: null,
            points: 145,
            createdAt: new Date('2024-01-05').toISOString(),
        },
        {
            email: 'aditya.kapoor@student.college.edu',
            password: 'student123',
            role: 'student',
            name: 'Aditya Kapoor',
            branch: 'Civil',
            rollNumber: '2022CIV023',
            semester: '5',
            year: '2022',
            gender: 'male',
            dob: '2003-09-16',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=aditya',
            phoneNumber: '+91-8432109876',
            department: null,
            points: 100,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        // TECHNICAL TEAM MEMBERS (5 records)
        {
            email: 'rajesh.kumar@tech.college.edu',
            password: 'tech123',
            role: 'technical',
            name: 'Rajesh Kumar',
            branch: null,
            rollNumber: null,
            semester: null,
            year: null,
            gender: 'male',
            dob: '1990-04-15',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=rajesh',
            phoneNumber: '+91-9988776655',
            department: 'electrical',
            points: 180,
            createdAt: new Date('2023-08-01').toISOString(),
        },
        {
            email: 'suresh.babu@tech.college.edu',
            password: 'tech123',
            role: 'technical',
            name: 'Suresh Babu',
            branch: null,
            rollNumber: null,
            semester: null,
            year: null,
            gender: 'male',
            dob: '1988-12-22',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=suresh',
            phoneNumber: '+91-9877665544',
            department: 'mechanical',
            points: 165,
            createdAt: new Date('2023-07-15').toISOString(),
        },
        {
            email: 'manoj.singh@tech.college.edu',
            password: 'tech123',
            role: 'technical',
            name: 'Manoj Singh',
            branch: null,
            rollNumber: null,
            semester: null,
            year: null,
            gender: 'male',
            dob: '1992-06-10',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=manoj',
            phoneNumber: '+91-9766554433',
            department: 'networking',
            points: 195,
            createdAt: new Date('2023-09-10').toISOString(),
        },
        {
            email: 'ramesh.verma@tech.college.edu',
            password: 'tech123',
            role: 'technical',
            name: 'Ramesh Verma',
            branch: null,
            rollNumber: null,
            semester: null,
            year: null,
            gender: 'male',
            dob: '1995-03-08',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=ramesh',
            phoneNumber: '+91-9655443322',
            department: 'plumbing',
            points: 120,
            createdAt: new Date('2023-10-05').toISOString(),
        },
        {
            email: 'sanjay.patel@tech.college.edu',
            password: 'tech123',
            role: 'technical',
            name: 'Sanjay Patel',
            branch: null,
            rollNumber: null,
            semester: null,
            year: null,
            gender: 'male',
            dob: '1991-08-25',
            profilePicture: 'https://avatar.iran.liara.run/public/boy?username=sanjay',
            phoneNumber: '+91-9544332211',
            department: 'civil',
            points: 155,
            createdAt: new Date('2023-08-20').toISOString(),
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});